### PR TITLE
Gentx for POSTHUMAN

### PR DESCRIPTION
**Pull request by cybernekit**

### CODE REVIEW

**Comment by dimiandre** [comment]
there is a typo in your validator details "ull-time"

**Comment by sunnya97** [comment]
@cybernekit Also, two things:
1.  Please move this into a `osmosis-1/gentxs/` folder.
2. Your commission rate is invalid.  As mentioned in the validator docs, Osmosis requires a minimum 5% commission rate.  This is enforced on chain.

**Review by sunnya97 — CHANGES_REQUESTED** [review]
@cybernekit Also, two things:
1.  Please move this into a `osmosis-1/gentxs/` folder.
2. Your commission rate is invalid.  As mentioned in the validator docs, Osmosis requires a minimum 5% commission rate.  This is enforced on chain.

**Comment by cybernekit** [comment]
will change

**Comment by sunnya97** [comment]
@cybernekit  Can you please move the file from `osmosis-1/gentx/` to `osmosis-1/gentxs/`?  (needs to be plural).  Thanks!

**Pull request merged**
